# Generated by Django 5.0.6 on 2024-06-05 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guru',
            name='mapel',
        ),
        migrations.AddField(
            model_name='guru',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guru',
            name='mapel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guru_mapel1', to='administrator.mapel'),
        ),
        migrations.AddField(
            model_name='guru',
            name='mapel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guru_mapel2', to='administrator.mapel'),
        ),
        migrations.AlterField(
            model_name='guru',
            name='alamat',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Panitia'),
        ),
    ]
