# Generated by Django 5.0.6 on 2024-06-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_guru_mapel_guru_jenis_kelamin_guru_mapel1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal_pg',
            name='jurusan',
        ),
        migrations.AddField(
            model_name='soal_pg',
            name='jurusan_rpl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soal_pg',
            name='jurusan_tkr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soal_pg',
            name='nomor_soal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soal_pg',
            name='soal_pg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
