# Generated by Django 5.0.6 on 2024-06-29 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_soal_pg_pengguna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soalesai',
            name='jurusan_rpl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soalesai',
            name='jurusan_tkr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soalesai',
            name='kelas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soalesai',
            name='pengguna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
