# Generated by Django 5.0.6 on 2024-06-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_soalesai_jurusan_rpl_soalesai_jurusan_tkr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soalesai',
            name='nomor_soal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
